### ISSUE TITLE
bigrams.dat

### ISSUE THREAD

**Issue by Vilquid** [scienceetonnante/MCMC#1]
Je crois qu'il manque un fichier car j'obtiens ce code d'erreur (l14, decipher_MCMC.py):
![image](https://user-images.githubusercontent.com/60876471/115957988-8f3b3480-a52f-11eb-8e71-98454d867afe.png)

**Comment by Morad28** [comment]
Salut, tu dois changer la variable booléenne  `COUNT_BIGRAMS = False` en `COUNT_BIGRAMS = True` pour qu'il puisse te créer le fichier :) 

![image](https://user-images.githubusercontent.com/37418923/115961432-85590780-a516-11eb-9cbd-e7a799e0d768.png)

**Comment by Vilquid** [comment]
> Salut, tu dois changer la variable booléenne `COUNT_BIGRAMS = False` en `COUNT_BIGRAMS = True` pour qu'il puisse te créer le fichier :)
> 
> ![image](https://user-images.githubusercontent.com/37418923/115961432-85590780-a516-11eb-9cbd-e7a799e0d768.png)

Tu peux expliquer pourquoi stp ?

**Comment by Morad28** [comment]
> 
> 
> > Salut, tu dois changer la variable booléenne `COUNT_BIGRAMS = False` en `COUNT_BIGRAMS = True` pour qu'il puisse te créer le fichier :)
> > ![image](https://user-images.githubusercontent.com/37418923/115961432-85590780-a516-11eb-9cbd-e7a799e0d768.png)
> 
> Tu peux expliquer pourquoi stp ?

Le fichier est créé dans le "if" à la ligne 16, plus précisément dans la méthode `count_bigrams( ... )` à la ligne 19. Cette méthode provient du fichier text_utils.py.

**Comment by Vilquid** [comment]
> > > Salut, tu dois changer la variable booléenne `COUNT_BIGRAMS = False` en `COUNT_BIGRAMS = True` pour qu'il puisse te créer le fichier :)
> > > ![image](https://user-images.githubusercontent.com/37418923/115961432-85590780-a516-11eb-9cbd-e7a799e0d768.png)
> > 
> > 
> > Tu peux expliquer pourquoi stp ?
> 
> Le fichier est créé dans le "if" à la ligne 16, plus précisément dans la méthode `count_bigrams( ... )` à la ligne 19. Cette méthode provient du fichier text_utils.py.

Mdr je suis trop con. Mais du coup il faut repasser COUNT_BIGRAMS sur False après le premier run du programme ?

**Comment by Morad28** [comment]
> 
> 
> > > > Salut, tu dois changer la variable booléenne `COUNT_BIGRAMS = False` en `COUNT_BIGRAMS = True` pour qu'il puisse te créer le fichier :)
> > > > ![image](https://user-images.githubusercontent.com/37418923/115961432-85590780-a516-11eb-9cbd-e7a799e0d768.png)
> > > 
> > > 
> > > Tu peux expliquer pourquoi stp ?
> > 
> > 
> > Le fichier est créé dans le "if" à la ligne 16, plus précisément dans la méthode `count_bigrams( ... )` à la ligne 19. Cette méthode provient du fichier text_utils.py.
> 
> Mdr je suis trop con. Mais du coup il faut repasser COUNT_BIGRAMS sur False après le premier run du programme ?

Yep ! Comme le fichier est créé tu peux le remettre en `False`

**Comment by SylvainParise** [comment]
Bonjour, 

il a également besoin d'un fichier dictionnary.dat, qui est généré par create_dictionnary.py
Mais ce programme génère un fichier dictionnary.data.
J'imagine qu'en Windows, vous n'avez pas de problème, mais sous linux tous les caractères d'un nom de fichier sont importants. Aussi, il faut soit demander à create_dictionnary.py de générer un fichier dictionnary.dat, soit lire un fichier .data en ligne 182
(with open('dictionnary.dat**a**', 'rb') as filehandle:)

**Comment by Vilquid** [comment]
> Bonjour,
> 
> il a également besoin d'un fichier dictionnary.dat, qui est généré par create_dictionnary.py
> Mais ce programme génère un fichier dictionnary.data.
> J'imagine qu'en Windows, vous n'avez pas de problème, mais sous linux tous les caractères d'un nom de fichier sont importants. Aussi, il faut soit demander à create_dictionnary.py de générer un fichier dictionnary.dat, soit lire un fichier .data en ligne 182
> (with open('dictionnary.dat**a**', 'rb') as filehandle:)

J'ai exactement le même problème que toi (et j'essayais de le résoudre) alors que je suis sous Windows 10. Je continue à chercher.
