### ISSUE TITLE
Erreur de débutant

### ISSUE THREAD

**Issue by JeConnaisPas** [scienceetonnante/MCMC#3]
Bonjour, je ne connais pas du tout python et j'ai beau chercher, je ne parviens pas à utiliser le code.
Si quelqu'un pouvait me donner la marche a suivre svp.
Merci beaucoup :)

**Comment by maleko78** [comment]
Tien tu as tout les lien donc tu a besoin ici! Quand tu ne connais pas quelque chose, Youtube et Google sont tes meilleur amis!!!
https://www.jetbrains.com/fr-fr/pycharm/
https://www.python.org/
https://www.youtube.com/watch?v=oUJolR5bX6g&t=1106s

**Comment by JeConnaisPas** [comment]
Merci beaucoup je vais aller voir tout cela (J'ai regardé de nombreuses explications qui ne marchaient pas dans mon cas :/ )
