### ISSUE TITLE
dictionnary.dat

### ISSUE THREAD

**Issue by Vilquid** [scienceetonnante/MCMC#4]
J'obtiens ce problème-là. Quelqu'un peu le résoudre ?
![image](https://user-images.githubusercontent.com/60876471/117284401-f8586b80-ae90-11eb-950b-dc1a49ecada6.png)

**Comment by scienceetonnante** [comment]
Il faut d'abord créer le dictionnaire avec Create_dictionary, j'ai mis à jour le code et le readme
